### PR TITLE
ci: delete github actions

### PR DESCRIPTION
**Pull request by hi-rustin**

### CODE REVIEW

**Comment by hi-rustin** [comment]
> # [Codecov](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296?src=pr&el=h1) Report
> 
> > Merging [#296](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296?src=pr&el=desc) ([78c0b32](https://github.com/ti-community-infra/ti-community-bot/commit/78c0b322b1c87880595068e41cb4c326d22f8f48)) into [master](https://codecov.io/gh/ti-community-infra/ti-community-bot/commit/43bdb6b27bb609381afdf9517c95e2c7a74c459a?el=desc) ([43bdb6b](https://github.com/ti-community-infra/ti-community-bot/commit/43bdb6b27bb609381afdf9517c95e2c7a74c459a)) will **increase** coverage by `1.12%`.
> > The diff coverage is `n/a`.
> 
> [Impacted file tree graph](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296?src=pr&el=tree)
> 
> ```diff
> @@            Coverage Diff             @@
> ##           master     #296      +/-   ##
> ==========================================
> + Coverage   75.90%   77.02%   +1.12%     
> ==========================================
>   Files          32       32              
>   Lines         693      653      -40     
>   Branches      101       93       -8     
> ==========================================
> - Hits          526      503      -23     
> + Misses        167      136      -31     
> - Partials        0       14      +14     
> ```
> 
> [Impacted Files](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296?src=pr&el=tree) 	Coverage Δ 	
> [src/api/statistics/index.ts](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree#diff-c3JjL2FwaS9zdGF0aXN0aWNzL2luZGV4LnRz) 	`63.63% <0.00%> (-14.63%)` 	⬇️
> [src/api/member/index.ts](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree#diff-c3JjL2FwaS9tZW1iZXIvaW5kZXgudHM=) 	`63.15% <0.00%> (-11.85%)` 	⬇️
> [src/api/contributor/index.ts](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree#diff-c3JjL2FwaS9jb250cmlidXRvci9pbmRleC50cw==) 	`68.75% <0.00%> (-1.84%)` 	⬇️
> [src/api/sig/index.ts](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree#diff-c3JjL2FwaS9zaWcvaW5kZXgudHM=) 	`91.66% <0.00%> (-1.20%)` 	⬇️
> [src/services/sig/index.ts](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree#diff-c3JjL3NlcnZpY2VzL3NpZy9pbmRleC50cw==) 	`96.34% <0.00%> (-0.22%)` 	⬇️
> [src/services/pull/index.ts](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree#diff-c3JjL3NlcnZpY2VzL3B1bGwvaW5kZXgudHM=) 	`100.00% <0.00%> (ø)` 	
> [src/services/member/index.ts](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree#diff-c3JjL3NlcnZpY2VzL21lbWJlci9pbmRleC50cw==) 	`100.00% <0.00%> (ø)` 	
> [src/services/statistics/index.ts](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree#diff-c3JjL3NlcnZpY2VzL3N0YXRpc3RpY3MvaW5kZXgudHM=) 	`100.00% <0.00%> (ø)` 	
> [src/services/contributor/index.ts](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree#diff-c3JjL3NlcnZpY2VzL2NvbnRyaWJ1dG9yL2luZGV4LnRz) 	`100.00% <0.00%> (ø)` 	
> [src/index.ts](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree#diff-c3JjL2luZGV4LnRz) 	`73.46% <0.00%> (+0.92%)` 	⬆️
> ... and [5 more](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296/diff?src=pr&el=tree-more) 		
> 
> [Continue to review full report at Codecov](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296?src=pr&el=continue).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296?src=pr&el=footer). Last update [43bdb6b...78c0b32](https://codecov.io/gh/ti-community-infra/ti-community-bot/pull/296?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

Finally!

**Comment by hi-rustin** [comment]
/assign @Mini256 

PTAL~ Thanks!

**Review by Mini256 — APPROVED** [review]

**Pull request merged**
